### ISSUE TITLE
FATAL: Module rbd not found.

### ISSUE THREAD

**Issue by david-igou** [serverbaboon/rook-arm64#1]
In your readme you say this is done on a Pi 4 - Is this on Raspbian? OOTB, the rbd module is not included. 

Did you compile the module yourself and add it, or are you using a different distro?

**Comment by serverbaboon** [comment]
Sorry I should have documented that.

Rook does not have images for ARMF, I know that the latest Raspbian version has a 64bit kernal option but the userland is(was?) 32bit and I did not want to get in a weird situation of 64bit kernal with 32bit userland running 64bit k3s.

So I have tested on the Raspberry pi Ubuntu 64bit images for 18.04LTS and 19.10.

https://ubuntu.com/download/server/arm

**Comment by serverbaboon** [comment]
I have updated the readme to reflect that.

**Comment by david-igou** [comment]
Yeah, I'm running Raspbian aarch64. The latest build doesn't come with the rbd module, though. You have to recompile with `CONFIG_CEPH_LIB=m, CONFIG_CEPH_LIB=m, and CONFIG_CEPH_FS=m` it seems.

**Comment by serverbaboon** [comment]
Is there a 64bit userland now?

Never tried compiling my own kernal, I am not sure I am that level.
